language: node_js
node_js: '10'
sudo: false
install: npm install
script:
- npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  project: alexandrtovmach-1534514719962
  token:
    secure: f0yyLTp6Kygc8NscGpneUeZN+H5wEUPpsmNNyZ0kKxzcIOTNamnan53qSBaLQq1LXygX3nmh4d/nYdTcRj8ohCxhuZlDI8zKG0XRteDj9YBqnupXZPnGEM1D6A6ZAqVrxHxLv9nhz0iQqv7EV3dxE5eMptRiswJPbsnVg4vnDnEo6h+wKljNDRgrynLbkU3PzNY2/tdnKJSEa/1GiDskkqZAVH1jd/Zgq021y2TwAw96JgJQDJB+z4q63tC5NigpwRPTHdMnCmNN9HYd/NsmwVfxJUZ14hHGPoUINW9ZSTUtqAgXMKcpthcwob9bj2YtQAdCV4XtC75hylmLwB0WfzUtMA5sKU3J4CU2WSgcqO1o9z+zEsbCIjZ/b7f1jgYKT/0OXBcF8Nn15iCwQyUxuGEW1t8XkGyakKwJxL4KVjfCj8CydmjUGjr3s73DbIlWaYIVDLmefuIW91UC6Kz1ChiUysO1GjjRwqm8gyjN/3UvgJytCWxgY03NoQ7ZEemiNFdiYpaM1yAD+JGHRLjX4rxAWoIBFyUJzcuQZjI1aGqG2/8Xxr/rERvx8t8kryMBcvYrZPzgJf5iPcwJIP5uxPJPOpQldOn7HdYEn0xY34k9QfjyYeNOzPVN19UIzFjFJRyFmfQ4dRK9lX0sZIXC0D0zxv4jtMMZV9atb9jnSzA=
branches:
  only:
  - master